# Generated by Django 5.2.8 on 2025-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_dustsensor_lightsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(editable=False)),
                ('value', models.FloatField()),
            ],
        ),
    ]
