# Generated by Django 5.2.8 on 2025-11-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_rainsensor'),
    ]

    operations = [
    ]
