# Generated by Django 5.2.8 on 2025-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20251129_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(editable=False)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
