# Generated by Django 5.2.8 on 2025-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_dirsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=10)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
